config/routes.rb
Illbillyrecords::Application.routes.draw do
  resources :songs

  resources :orders

  resources :payment_methods

  resources :shipping_options

  resources :purchases

  resources :users

  resources :used_vinyls

  resources :releases

  root :to => "home#index"
  get "home/index"

end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  attr_accessible :name
  has_many :orders
  has_many :users
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_methods }
    end
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
    @payment_method = PaymentMethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_method }
    end
  end

  # GET /payment_methods/new
  # GET /payment_methods/new.json
  def new
    @payment_method = PaymentMethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_method }
    end
  end

  # GET /payment_methods/1/edit
  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(params[:payment_method])

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render json: @payment_method, status: :created, location: @payment_method }
      else
        format.html { render action: "new" }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payment_methods/1
  # PUT /payment_methods/1.json
  def update
    @payment_method = PaymentMethod.find(params[:id])

    respond_to do |format|
      if @payment_method.update_attributes(params[:payment_method])
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy

    respond_to do |format|
      format.html { redirect_to payment_methods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_for(@payment_method) do |f| %>
  <% if @payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% @payment_method.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing payment_method</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<h1>Listing payment_methods</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_methods.each do |payment_method| %>
  <tr>
    <td><%= payment_method.name %></td>
    <td><%= link_to 'Show', payment_method %></td>
    <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
    <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New payment_method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @payment_method.name %>
</p>


<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>