config/routes.rb
Illbillyrecords::Application.routes.draw do
  resources :songs

  resources :orders

  resources :payment_methods

  resources :shipping_options

  resources :purchases

  resources :users

  resources :used_vinyls

  resources :releases

  root :to => "home#index"
  get "home/index"

end

app/models/used_vinyl.rb
class UsedVinyl < ActiveRecord::Base
  attr_accessible :album, :artist, :price, :price, :purchased, :type
  has_many :purchases
end

app/controllers/used_vinyls_controller.rb
class UsedVinylsController < ApplicationController
  # GET /used_vinyls
  # GET /used_vinyls.json
  def index
    @used_vinyls = UsedVinyl.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @used_vinyls }
    end
  end

  # GET /used_vinyls/1
  # GET /used_vinyls/1.json
  def show
    @used_vinyl = UsedVinyl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @used_vinyl }
    end
  end

  # GET /used_vinyls/new
  # GET /used_vinyls/new.json
  def new
    @used_vinyl = UsedVinyl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @used_vinyl }
    end
  end

  # GET /used_vinyls/1/edit
  def edit
    @used_vinyl = UsedVinyl.find(params[:id])
  end

  # POST /used_vinyls
  # POST /used_vinyls.json
  def create
    @used_vinyl = UsedVinyl.new(params[:used_vinyl])

    respond_to do |format|
      if @used_vinyl.save
        format.html { redirect_to @used_vinyl, notice: 'Used vinyl was successfully created.' }
        format.json { render json: @used_vinyl, status: :created, location: @used_vinyl }
      else
        format.html { render action: "new" }
        format.json { render json: @used_vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /used_vinyls/1
  # PUT /used_vinyls/1.json
  def update
    @used_vinyl = UsedVinyl.find(params[:id])

    respond_to do |format|
      if @used_vinyl.update_attributes(params[:used_vinyl])
        format.html { redirect_to @used_vinyl, notice: 'Used vinyl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @used_vinyl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /used_vinyls/1
  # DELETE /used_vinyls/1.json
  def destroy
    @used_vinyl = UsedVinyl.find(params[:id])
    @used_vinyl.destroy

    respond_to do |format|
      format.html { redirect_to used_vinyls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/used_vinyls_helper.rb
module UsedVinylsHelper
end

app/views/used_vinyls/_form.html.erb
<%= form_for(@used_vinyl) do |f| %>
  <% if @used_vinyl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@used_vinyl.errors.count, "error") %> prohibited this used_vinyl from being saved:</h2>

      <ul>
      <% @used_vinyl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album %><br />
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :purchased %><br />
    <%= f.check_box :purchased %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/used_vinyls/edit.html.erb
<h1>Editing used_vinyl</h1>

<%= render 'form' %>

<%= link_to 'Show', @used_vinyl %> |
<%= link_to 'Back', used_vinyls_path %>

app/views/used_vinyls/index.html.erb
<h1>Listing used_vinyls</h1>

<table>
  <tr>
    <th>Album</th>
    <th>Artist</th>
    <th>Type</th>
    <th>Purchased</th>
    <th>Price</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @used_vinyls.each do |used_vinyl| %>
  <tr>
    <td><%= used_vinyl.album %></td>
    <td><%= used_vinyl.artist %></td>
    <td><%= used_vinyl.type %></td>
    <td><%= used_vinyl.purchased %></td>
    <td><%= used_vinyl.price %></td>
    <td><%= used_vinyl.price %></td>
    <td><%= link_to 'Show', used_vinyl %></td>
    <td><%= link_to 'Edit', edit_used_vinyl_path(used_vinyl) %></td>
    <td><%= link_to 'Destroy', used_vinyl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Used vinyl', new_used_vinyl_path %>

app/views/used_vinyls/new.html.erb
<h1>New used_vinyl</h1>

<%= render 'form' %>

<%= link_to 'Back', used_vinyls_path %>

app/views/used_vinyls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Album:</b>
  <%= @used_vinyl.album %>
</p>

<p>
  <b>Artist:</b>
  <%= @used_vinyl.artist %>
</p>

<p>
  <b>Type:</b>
  <%= @used_vinyl.type %>
</p>

<p>
  <b>Purchased:</b>
  <%= @used_vinyl.purchased %>
</p>

<p>
  <b>Price:</b>
  <%= @used_vinyl.price %>
</p>

<p>
  <b>Price:</b>
  <%= @used_vinyl.price %>
</p>


<%= link_to 'Edit', edit_used_vinyl_path(@used_vinyl) %> |
<%= link_to 'Back', used_vinyls_path %>